export const countryData = [
  {
    name: 'Afghanistan',
    dial_code: '+93',
    code: 'AF',
    flag: require('../assets/images/flags/af.png'),
  },
  {
    name: 'Aland Islands',
    dial_code: '+358',
    code: 'AX',
    flag: require('../assets/images/flags/ax.png'),
  },
  {
    name: 'Albania',
    dial_code: '+355',
    code: 'AL',
    flag: require('../assets/images/flags/al.png'),
  },
  {
    name: 'Algeria',
    dial_code: '+213',
    code: 'DZ',
    flag: require('../assets/images/flags/dz.png'),
  },
  {
    name: 'American Samoa',
    dial_code: '+1684',
    code: 'AS',
    flag: require('../assets/images/flags/as.png'),
  },
  {
    name: 'Andorra',
    dial_code: '+376',
    code: 'AD',
    flag: require('../assets/images/flags/ad.png'),
  },
  {
    name: 'Angola',
    dial_code: '+244',
    code: 'AO',
    flag: require('../assets/images/flags/ao.png'),
  },
  {
    name: 'Anguilla',
    dial_code: '+1264',
    code: 'AI',
    flag: require('../assets/images/flags/ai.png'),
  },
  {
    name: 'Antarctica',
    dial_code: '+672',
    code: 'AQ',
    flag: require('../assets/images/flags/aq.png'),
  },
  {
    name: 'Antigua and Barbuda',
    dial_code: '+1268',
    code: 'AG',
    flag: require('../assets/images/flags/ag.png'),
  },
  {
    name: 'Argentina',
    dial_code: '+54',
    code: 'AR',
    flag: require('../assets/images/flags/ar.png'),
  },
  {
    name: 'Armenia',
    dial_code: '+374',
    code: 'AM',
    flag: require('../assets/images/flags/am.png'),
  },
  {
    name: 'Aruba',
    dial_code: '+297',
    code: 'AW',
    flag: require('../assets/images/flags/aw.png'),
  },
  {
    name: 'Australia',
    dial_code: '+61',
    code: 'AU',
    flag: require('../assets/images/flags/au.png'),
  },
  {
    name: 'Austria',
    dial_code: '+43',
    code: 'AT',
    flag: require('../assets/images/flags/at.png'),
  },
  {
    name: 'Azerbaijan',
    dial_code: '+994',
    code: 'AZ',
    flag: require('../assets/images/flags/az.png'),
  },
  {
    name: 'Bahamas',
    dial_code: '+1242',
    code: 'BS',
    flag: require('../assets/images/flags/bs.png'),
  },
  {
    name: 'Bahrain',
    dial_code: '+973',
    code: 'BH',
    flag: require('../assets/images/flags/bh.png'),
  },
  {
    name: 'Bangladesh',
    dial_code: '+880',
    code: 'BD',
    flag: require('../assets/images/flags/bd.png'),
  },
  {
    name: 'Barbados',
    dial_code: '+1246',
    code: 'BB',
    flag: require('../assets/images/flags/bb.png'),
  },
  {
    name: 'Belarus',
    dial_code: '+375',
    code: 'BY',
    flag: require('../assets/images/flags/by.png'),
  },
  {
    name: 'Belgium',
    dial_code: '+32',
    code: 'BE',
    flag: require('../assets/images/flags/be.png'),
  },
  {
    name: 'Belize',
    dial_code: '+501',
    code: 'BZ',
    flag: require('../assets/images/flags/bz.png'),
  },
  {
    name: 'Benin',
    dial_code: '+229',
    code: 'BJ',
    flag: require('../assets/images/flags/bj.png'),
  },
  {
    name: 'Bermuda',
    dial_code: '+1441',
    code: 'BM',
    flag: require('../assets/images/flags/bm.png'),
  },
  {
    name: 'Bhutan',
    dial_code: '+975',
    code: 'BT',
    flag: require('../assets/images/flags/bt.png'),
  },
  {
    name: 'Bolivia, Plurinational State of',
    dial_code: '+591',
    code: 'BO',
    flag: require('../assets/images/flags/bo.png'),
  },
  {
    name: 'Bosnia and Herzegovina',
    dial_code: '+387',
    code: 'BA',
    flag: require('../assets/images/flags/ba.png'),
  },
  {
    name: 'Botswana',
    dial_code: '+267',
    code: 'BW',
    flag: require('../assets/images/flags/bw.png'),
  },
  {
    name: 'Brazil',
    dial_code: '+55',
    code: 'BR',
    flag: require('../assets/images/flags/br.png'),
  },
  {
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    code: 'IO',
    flag: require('../assets/images/flags/io.png'),
  },
  {
    name: 'Brunei Darussalam',
    dial_code: '+673',
    code: 'BN',
    flag: require('../assets/images/flags/bn.png'),
  },
  {
    name: 'Bulgaria',
    dial_code: '+359',
    code: 'BG',
    flag: require('../assets/images/flags/bg.png'),
  },
  {
    name: 'Burkina Faso',
    dial_code: '+226',
    code: 'BF',
    flag: require('../assets/images/flags/bf.png'),
  },
  {
    name: 'Burundi',
    dial_code: '+257',
    code: 'BI',
    flag: require('../assets/images/flags/bi.png'),
  },
  {
    name: 'Cambodia',
    dial_code: '+855',
    code: 'KH',
    flag: require('../assets/images/flags/kh.png'),
  },
  {
    name: 'Cameroon',
    dial_code: '+237',
    code: 'CM',
    flag: require('../assets/images/flags/cm.png'),
  },
  {
    name: 'Canada',
    dial_code: '+1',
    code: 'CA',
    flag: require('../assets/images/flags/ca.png'),
  },
  {
    name: 'Cape Verde',
    dial_code: '+238',
    code: 'CV',
    flag: require('../assets/images/flags/cv.png'),
  },
  {
    name: 'Cayman Islands',
    dial_code: '+1345',
    code: 'KY',
    flag: require('../assets/images/flags/ky.png'),
  },
  {
    name: 'Central African Republic',
    dial_code: '+236',
    code: 'CF',
    flag: require('../assets/images/flags/cf.png'),
  },
  {
    name: 'Chad',
    dial_code: '+235',
    code: 'TD',
    flag: require('../assets/images/flags/td.png'),
  },
  {
    name: 'Chile',
    dial_code: '+56',
    code: 'CL',
    flag: require('../assets/images/flags/cl.png'),
  },
  {
    name: 'China',
    dial_code: '+86',
    code: 'CN',
    flag: require('../assets/images/flags/cn.png'),
  },
  {
    name: 'Christmas Island',
    dial_code: '+61',
    code: 'CX',
    flag: require('../assets/images/flags/cx.png'),
  },
  {
    name: 'Cocos (Keeling) Islands',
    dial_code: '+61',
    code: 'CC',
    flag: require('../assets/images/flags/cc.png'),
  },
  {
    name: 'Colombia',
    dial_code: '+57',
    code: 'CO',
    flag: require('../assets/images/flags/co.png'),
  },
  {
    name: 'Comoros',
    dial_code: '+269',
    code: 'KM',
    flag: require('../assets/images/flags/km.png'),
  },
  {
    name: 'Congo',
    dial_code: '+242',
    code: 'CG',
    flag: require('../assets/images/flags/cg.png'),
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    dial_code: '+243',
    code: 'CD',
    flag: require('../assets/images/flags/cd.png'),
  },
  {
    name: 'Cook Islands',
    dial_code: '+682',
    code: 'CK',
    flag: require('../assets/images/flags/ck.png'),
  },
  {
    name: 'Costa Rica',
    dial_code: '+506',
    code: 'CR',
    flag: require('../assets/images/flags/cr.png'),
  },
  {
    name: "Cote d'Ivoire",
    dial_code: '+225',
    code: 'CI',
    flag: require('../assets/images/flags/ci.png'),
  },
  {
    name: 'Croatia',
    dial_code: '+385',
    code: 'HR',
    flag: require('../assets/images/flags/hr.png'),
  },
  {
    name: 'Cuba',
    dial_code: '+53',
    code: 'CU',
    flag: require('../assets/images/flags/cu.png'),
  },
  {
    name: 'Cyprus',
    dial_code: '+357',
    code: 'CY',
    flag: require('../assets/images/flags/cy.png'),
  },
  {
    name: 'Czech Republic',
    dial_code: '+420',
    code: 'CZ',
    flag: require('../assets/images/flags/cz.png'),
  },
  {
    name: 'Denmark',
    dial_code: '+45',
    code: 'DK',
    flag: require('../assets/images/flags/dk.png'),
  },
  {
    name: 'Djibouti',
    dial_code: '+253',
    code: 'DJ',
    flag: require('../assets/images/flags/dj.png'),
  },
  {
    name: 'Dominica',
    dial_code: '+1767',
    code: 'DM',
    flag: require('../assets/images/flags/dm.png'),
  },
  {
    name: 'Dominican Republic',
    dial_code: '+1849',
    code: 'DO',
    flag: require('../assets/images/flags/do.png'),
  },
  {
    name: 'Ecuador',
    dial_code: '+593',
    code: 'EC',
    flag: require('../assets/images/flags/ec.png'),
  },
  {
    name: 'Egypt',
    dial_code: '+20',
    code: 'EG',
    flag: require('../assets/images/flags/eg.png'),
  },
  {
    name: 'El Salvador',
    dial_code: '+503',
    code: 'SV',
    flag: require('../assets/images/flags/sv.png'),
  },
  {
    name: 'Equatorial Guinea',
    dial_code: '+240',
    code: 'GQ',
    flag: require('../assets/images/flags/gq.png'),
  },
  {
    name: 'Eritrea',
    dial_code: '+291',
    code: 'ER',
    flag: require('../assets/images/flags/er.png'),
  },
  {
    name: 'Estonia',
    dial_code: '+372',
    code: 'EE',
    flag: require('../assets/images/flags/ee.png'),
  },
  {
    name: 'Ethiopia',
    dial_code: '+251',
    code: 'ET',
    flag: require('../assets/images/flags/et.png'),
  },
  {
    name: 'Falkland Islands (Malvinas)',
    dial_code: '+500',
    code: 'FK',
    flag: require('../assets/images/flags/fk.png'),
  },
  {
    name: 'Faroe Islands',
    dial_code: '+298',
    code: 'FO',
    flag: require('../assets/images/flags/fo.png'),
  },
  {
    name: 'Fiji',
    dial_code: '+679',
    code: 'FJ',
    flag: require('../assets/images/flags/fj.png'),
  },
  {
    name: 'Finland',
    dial_code: '+358',
    code: 'FI',
    flag: require('../assets/images/flags/fi.png'),
  },
  {
    name: 'France',
    dial_code: '+33',
    code: 'FR',
    flag: require('../assets/images/flags/fr.png'),
  },
  {
    name: 'French Guiana',
    dial_code: '+594',
    code: 'GF',
    flag: require('../assets/images/flags/gf.png'),
  },
  {
    name: 'French Polynesia',
    dial_code: '+689',
    code: 'PF',
    flag: require('../assets/images/flags/pf.png'),
  },
  {
    name: 'Gabon',
    dial_code: '+241',
    code: 'GA',
    flag: require('../assets/images/flags/ga.png'),
  },
  {
    name: 'Gambia',
    dial_code: '+220',
    code: 'GM',
    flag: require('../assets/images/flags/gm.png'),
  },
  {
    name: 'Georgia',
    dial_code: '+995',
    code: 'GE',
    flag: require('../assets/images/flags/ge.png'),
  },
  {
    name: 'Germany',
    dial_code: '+49',
    code: 'DE',
    flag: require('../assets/images/flags/de.png'),
  },
  {
    name: 'Ghana',
    dial_code: '+233',
    code: 'GH',
    flag: require('../assets/images/flags/gh.png'),
  },
  {
    name: 'Gibraltar',
    dial_code: '+350',
    code: 'GI',
    flag: require('../assets/images/flags/gi.png'),
  },
  {
    name: 'Greece',
    dial_code: '+30',
    code: 'GR',
    flag: require('../assets/images/flags/gr.png'),
  },
  {
    name: 'Greenland',
    dial_code: '+299',
    code: 'GL',
    flag: require('../assets/images/flags/gl.png'),
  },
  {
    name: 'Grenada',
    dial_code: '+1473',
    code: 'GD',
    flag: require('../assets/images/flags/gd.png'),
  },
  {
    name: 'Guadeloupe',
    dial_code: '+590',
    code: 'GP',
    flag: require('../assets/images/flags/gp.png'),
  },
  {
    name: 'Guam',
    dial_code: '+1671',
    code: 'GU',
    flag: require('../assets/images/flags/gu.png'),
  },
  {
    name: 'Guatemala',
    dial_code: '+502',
    code: 'GT',
    flag: require('../assets/images/flags/gt.png'),
  },
  {
    name: 'Guernsey',
    dial_code: '+44',
    code: 'GG',
    flag: require('../assets/images/flags/gg.png'),
  },
  {
    name: 'Guinea',
    dial_code: '+224',
    code: 'GN',
    flag: require('../assets/images/flags/gn.png'),
  },
  {
    name: 'Guinea-Bissau',
    dial_code: '+245',
    code: 'GW',
    flag: require('../assets/images/flags/gw.png'),
  },
  {
    name: 'Guyana',
    dial_code: '+595',
    code: 'GY',
    flag: require('../assets/images/flags/gy.png'),
  },
  {
    name: 'Haiti',
    dial_code: '+509',
    code: 'HT',
    flag: require('../assets/images/flags/ht.png'),
  },
  {
    name: 'Holy See (Vatican City State)',
    dial_code: '+379',
    code: 'VA',
    flag: require('../assets/images/flags/va.png'),
  },
  {
    name: 'Honduras',
    dial_code: '+504',
    code: 'HN',
    flag: require('../assets/images/flags/hn.png'),
  },
  {
    name: 'Hong Kong',
    dial_code: '+852',
    code: 'HK',
    flag: require('../assets/images/flags/hk.png'),
  },
  {
    name: 'Hungary',
    dial_code: '+36',
    code: 'HU',
    flag: require('../assets/images/flags/hu.png'),
  },
  {
    name: 'Iceland',
    dial_code: '+354',
    code: 'IS',
    flag: require('../assets/images/flags/is.png'),
  },
  {
    name: 'India',
    dial_code: '+91',
    code: 'IN',
    flag: require('../assets/images/flags/in.png'),
  },
  {
    name: 'Indonesia',
    dial_code: '+62',
    code: 'ID',
    flag: require('../assets/images/flags/id.png'),
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    dial_code: '+98',
    code: 'IR',
    flag: require('../assets/images/flags/ir.png'),
  },
  {
    name: 'Iraq',
    dial_code: '+964',
    code: 'IQ',
    flag: require('../assets/images/flags/iq.png'),
  },
  {
    name: 'Ireland',
    dial_code: '+353',
    code: 'IE',
    flag: require('../assets/images/flags/ie.png'),
  },
  {
    name: 'Isle of Man',
    dial_code: '+44',
    code: 'IM',
    flag: require('../assets/images/flags/im.png'),
  },
  {
    name: 'Israel',
    dial_code: '+972',
    code: 'IL',
    flag: require('../assets/images/flags/il.png'),
  },
  {
    name: 'Italy',
    dial_code: '+39',
    code: 'IT',
    flag: require('../assets/images/flags/it.png'),
  },
  {
    name: 'Jamaica',
    dial_code: '+1876',
    code: 'JM',
    flag: require('../assets/images/flags/jm.png'),
  },
  {
    name: 'Japan',
    dial_code: '+81',
    code: 'JP',
    flag: require('../assets/images/flags/jp.png'),
  },
  {
    name: 'Jersey',
    dial_code: '+44',
    code: 'JE',
    flag: require('../assets/images/flags/je.png'),
  },
  {
    name: 'Jordan',
    dial_code: '+962',
    code: 'JO',
    flag: require('../assets/images/flags/jo.png'),
  },
  {
    name: 'Kazakhstan',
    dial_code: '+77',
    code: 'KZ',
    flag: require('../assets/images/flags/kz.png'),
  },
  {
    name: 'Kenya',
    dial_code: '+254',
    code: 'KE',
    flag: require('../assets/images/flags/ke.png'),
  },
  {
    name: 'Kiribati',
    dial_code: '+686',
    code: 'KI',
    flag: require('../assets/images/flags/ki.png'),
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: '+850',
    code: 'KP',
    flag: require('../assets/images/flags/kp.png'),
  },
  {
    name: 'Korea, Republic of South Korea',
    dial_code: '+82',
    code: 'KR',
    flag: require('../assets/images/flags/kr.png'),
  },
  {
    name: 'Kuwait',
    dial_code: '+965',
    code: 'KW',
    flag: require('../assets/images/flags/kw.png'),
  },
  {
    name: 'Kyrgyzstan',
    dial_code: '+996',
    code: 'KG',
    flag: require('../assets/images/flags/kg.png'),
  },
  {
    name: 'Laos',
    dial_code: '+856',
    code: 'LA',
    flag: require('../assets/images/flags/la.png'),
  },
  {
    name: 'Latvia',
    dial_code: '+371',
    code: 'LV',
    flag: require('../assets/images/flags/lv.png'),
  },
  {
    name: 'Lebanon',
    dial_code: '+961',
    code: 'LB',
    flag: require('../assets/images/flags/lb.png'),
  },
  {
    name: 'Lesotho',
    dial_code: '+266',
    code: 'LS',
    flag: require('../assets/images/flags/ls.png'),
  },
  {
    name: 'Liberia',
    dial_code: '+231',
    code: 'LR',
    flag: require('../assets/images/flags/lr.png'),
  },
  {
    name: 'Libyan Arab Jamahiriya',
    dial_code: '+218',
    code: 'LY',
    flag: require('../assets/images/flags/ly.png'),
  },
  {
    name: 'Liechtenstein',
    dial_code: '+423',
    code: 'LI',
    flag: require('../assets/images/flags/li.png'),
  },
  {
    name: 'Lithuania',
    dial_code: '+370',
    code: 'LT',
    flag: require('../assets/images/flags/lt.png'),
  },
  {
    name: 'Luxembourg',
    dial_code: '+352',
    code: 'LU',
    flag: require('../assets/images/flags/lu.png'),
  },
  {
    name: 'Macao',
    dial_code: '+853',
    code: 'MO',
    flag: require('../assets/images/flags/mo.png'),
  },
  {
    name: 'Macedonia',
    dial_code: '+389',
    code: 'MK',
    flag: require('../assets/images/flags/mk.png'),
  },
  {
    name: 'Madagascar',
    dial_code: '+261',
    code: 'MG',
    flag: require('../assets/images/flags/mg.png'),
  },
  {
    name: 'Malawi',
    dial_code: '+265',
    code: 'MW',
    flag: require('../assets/images/flags/mw.png'),
  },
  {
    name: 'Malaysia',
    dial_code: '+60',
    code: 'MY',
    flag: require('../assets/images/flags/my.png'),
  },
  {
    name: 'Maldives',
    dial_code: '+960',
    code: 'MV',
    flag: require('../assets/images/flags/mv.png'),
  },
  {
    name: 'Mali',
    dial_code: '+223',
    code: 'ML',
    flag: require('../assets/images/flags/ml.png'),
  },
  {
    name: 'Malta',
    dial_code: '+356',
    code: 'MT',
    flag: require('../assets/images/flags/mt.png'),
  },
  {
    name: 'Marshall Islands',
    dial_code: '+692',
    code: 'MH',
    flag: require('../assets/images/flags/mh.png'),
  },
  {
    name: 'Martinique',
    dial_code: '+596',
    code: 'MQ',
    flag: require('../assets/images/flags/mq.png'),
  },
  {
    name: 'Mauritania',
    dial_code: '+222',
    code: 'MR',
    flag: require('../assets/images/flags/mr.png'),
  },
  {
    name: 'Mauritius',
    dial_code: '+230',
    code: 'MU',
    flag: require('../assets/images/flags/mu.png'),
  },
  {
    name: 'Mayotte',
    dial_code: '+262',
    code: 'YT',
    flag: require('../assets/images/flags/yt.png'),
  },
  {
    name: 'Mexico',
    dial_code: '+52',
    code: 'MX',
    flag: require('../assets/images/flags/mx.png'),
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    dial_code: '+691',
    code: 'FM',
    flag: require('../assets/images/flags/fm.png'),
  },
  {
    name: 'Moldova',
    dial_code: '+373',
    code: 'MD',
    flag: require('../assets/images/flags/md.png'),
  },
  {
    name: 'Monaco',
    dial_code: '+377',
    code: 'MC',
    flag: require('../assets/images/flags/mc.png'),
  },
  {
    name: 'Mongolia',
    dial_code: '+976',
    code: 'MN',
    flag: require('../assets/images/flags/mn.png'),
  },
  {
    name: 'Montenegro',
    dial_code: '+382',
    code: 'ME',
    flag: require('../assets/images/flags/me.png'),
  },
  {
    name: 'Montserrat',
    dial_code: '+1664',
    code: 'MS',
    flag: require('../assets/images/flags/ms.png'),
  },
  {
    name: 'Morocco',
    dial_code: '+212',
    code: 'MA',
    flag: require('../assets/images/flags/ma.png'),
  },
  {
    name: 'Mozambique',
    dial_code: '+258',
    code: 'MZ',
    flag: require('../assets/images/flags/mz.png'),
  },
  {
    name: 'Myanmar',
    dial_code: '+95',
    code: 'MM',
    flag: require('../assets/images/flags/mm.png'),
  },
  {
    name: 'Namibia',
    dial_code: '+264',
    code: 'NA',
    flag: require('../assets/images/flags/na.png'),
  },
  {
    name: 'Nauru',
    dial_code: '+674',
    code: 'NR',
    flag: require('../assets/images/flags/nr.png'),
  },
  {
    name: 'Nepal',
    dial_code: '+977',
    code: 'NP',
    flag: require('../assets/images/flags/np.png'),
  },
  {
    name: 'Netherlands',
    dial_code: '+31',
    code: 'NL',
    flag: require('../assets/images/flags/nl.png'),
  },
  {
    name: 'New Caledonia',
    dial_code: '+687',
    code: 'NC',
    flag: require('../assets/images/flags/nc.png'),
  },
  {
    name: 'New Zealand',
    dial_code: '+64',
    code: 'NZ',
    flag: require('../assets/images/flags/nz.png'),
  },
  {
    name: 'Nicaragua',
    dial_code: '+505',
    code: 'NI',
    flag: require('../assets/images/flags/ni.png'),
  },
  {
    name: 'Niger',
    dial_code: '+227',
    code: 'NE',
    flag: require('../assets/images/flags/ne.png'),
  },
  {
    name: 'Nigeria',
    dial_code: '+234',
    code: 'NG',
    flag: require('../assets/images/flags/ng.png'),
  },
  {
    name: 'Niue',
    dial_code: '+683',
    code: 'NU',
    flag: require('../assets/images/flags/nu.png'),
  },
  {
    name: 'Norfolk Island',
    dial_code: '+672',
    code: 'NF',
    flag: require('../assets/images/flags/nf.png'),
  },
  {
    name: 'Northern Mariana Islands',
    dial_code: '+1670',
    code: 'MP',
    flag: require('../assets/images/flags/mp.png'),
  },
  {
    name: 'Norway',
    dial_code: '+47',
    code: 'NO',
    flag: require('../assets/images/flags/no.png'),
  },
  {
    name: 'Oman',
    dial_code: '+968',
    code: 'OM',
    flag: require('../assets/images/flags/om.png'),
  },
  {
    name: 'Pakistan',
    dial_code: '+92',
    code: 'PK',
    flag: require('../assets/images/flags/pk.png'),
  },
  {
    name: 'Palau',
    dial_code: '+680',
    code: 'PW',
    flag: require('../assets/images/flags/pw.png'),
  },
  {
    name: 'Palestinian Territory',
    dial_code: '+970',
    code: 'PS',
    flag: require('../assets/images/flags/ps.png'),
  },
  {
    name: 'Panama',
    dial_code: '+507',
    code: 'PA',
    flag: require('../assets/images/flags/pa.png'),
  },
  {
    name: 'Papua New Guinea',
    dial_code: '+675',
    code: 'PG',
    flag: require('../assets/images/flags/pg.png'),
  },
  {
    name: 'Paraguay',
    dial_code: '+595',
    code: 'PY',
    flag: require('../assets/images/flags/py.png'),
  },
  {
    name: 'Peru',
    dial_code: '+51',
    code: 'PE',
    flag: require('../assets/images/flags/pe.png'),
  },
  {
    name: 'Philippines',
    dial_code: '+63',
    code: 'PH',
    flag: require('../assets/images/flags/ph.png'),
  },
  {
    name: 'Pitcairn',
    dial_code: '+872',
    code: 'PN',
    flag: require('../assets/images/flags/pn.png'),
  },
  {
    name: 'Poland',
    dial_code: '+48',
    code: 'PL',
    flag: require('../assets/images/flags/pl.png'),
  },
  {
    name: 'Portugal',
    dial_code: '+351',
    code: 'PT',
    flag: require('../assets/images/flags/pt.png'),
  },
  {
    name: 'Puerto Rico',
    dial_code: '+1939',
    code: 'PR',
    flag: require('../assets/images/flags/pr.png'),
  },
  {
    name: 'Qatar',
    dial_code: '+974',
    code: 'QA',
    flag: require('../assets/images/flags/qa.png'),
  },
  {
    name: 'Romania',
    dial_code: '+40',
    code: 'RO',
    flag: require('../assets/images/flags/ro.png'),
  },
  {
    name: 'Russia',
    dial_code: '+7',
    code: 'RU',
    flag: require('../assets/images/flags/ru.png'),
  },
  {
    name: 'Rwanda',
    dial_code: '+250',
    code: 'RW',
    flag: require('../assets/images/flags/rw.png'),
  },
  {
    name: 'Reunion',
    dial_code: '+262',
    code: 'RE',
    flag: require('../assets/images/flags/re.png'),
  },
  {
    name: 'Saint Barthelemy',
    dial_code: '+590',
    code: 'BL',
    flag: require('../assets/images/flags/bl.png'),
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dial_code: '+290',
    code: 'SH',
    flag: require('../assets/images/flags/sh.png'),
  },
  {
    name: 'Saint Kitts and Nevis',
    dial_code: '+1869',
    code: 'KN',
    flag: require('../assets/images/flags/kn.png'),
  },
  {
    name: 'Saint Lucia',
    dial_code: '+1758',
    code: 'LC',
    flag: require('../assets/images/flags/lc.png'),
  },
  {
    name: 'Saint Martin',
    dial_code: '+590',
    code: 'MF',
    flag: require('../assets/images/flags/mf.png'),
  },
  {
    name: 'Saint Pierre and Miquelon',
    dial_code: '+508',
    code: 'PM',
    flag: require('../assets/images/flags/pm.png'),
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dial_code: '+1784',
    code: 'VC',
    flag: require('../assets/images/flags/vc.png'),
  },
  {
    name: 'Samoa',
    dial_code: '+685',
    code: 'WS',
    flag: require('../assets/images/flags/ws.png'),
  },
  {
    name: 'San Marino',
    dial_code: '+378',
    code: 'SM',
    flag: require('../assets/images/flags/sm.png'),
  },
  {
    name: 'Sao Tome and Principe',
    dial_code: '+239',
    code: 'ST',
    flag: require('../assets/images/flags/st.png'),
  },
  {
    name: 'Saudi Arabia',
    dial_code: '+966',
    code: 'SA',
    flag: require('../assets/images/flags/sa.png'),
  },
  {
    name: 'Senegal',
    dial_code: '+221',
    code: 'SN',
    flag: require('../assets/images/flags/sn.png'),
  },
  {
    name: 'Serbia',
    dial_code: '+381',
    code: 'RS',
    flag: require('../assets/images/flags/rs.png'),
  },
  {
    name: 'Seychelles',
    dial_code: '+248',
    code: 'SC',
    flag: require('../assets/images/flags/sc.png'),
  },
  {
    name: 'Sierra Leone',
    dial_code: '+232',
    code: 'SL',
    flag: require('../assets/images/flags/sl.png'),
  },
  {
    name: 'Singapore',
    dial_code: '+65',
    code: 'SG',
    flag: require('../assets/images/flags/sg.png'),
  },
  {
    name: 'Slovakia',
    dial_code: '+421',
    code: 'SK',
    flag: require('../assets/images/flags/sk.png'),
  },
  {
    name: 'Slovenia',
    dial_code: '+386',
    code: 'SI',
    flag: require('../assets/images/flags/si.png'),
  },
  {
    name: 'Solomon Islands',
    dial_code: '+677',
    code: 'SB',
    flag: require('../assets/images/flags/sb.png'),
  },
  {
    name: 'Somalia',
    dial_code: '+252',
    code: 'SO',
    flag: require('../assets/images/flags/so.png'),
  },
  {
    name: 'South Africa',
    dial_code: '+27',
    code: 'ZA',
    flag: require('../assets/images/flags/za.png'),
  },
  {
    name: 'South Sudan',
    dial_code: '+211',
    code: 'SS',
    flag: require('../assets/images/flags/ss.png'),
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dial_code: '+500',
    code: 'GS',
    flag: require('../assets/images/flags/gs.png'),
  },
  {
    name: 'Spain',
    dial_code: '+34',
    code: 'ES',
    flag: require('../assets/images/flags/es.png'),
  },
  {
    name: 'Sri Lanka',
    dial_code: '+94',
    code: 'LK',
    flag: require('../assets/images/flags/lk.png'),
  },
  {
    name: 'Sudan',
    dial_code: '+249',
    code: 'SD',
    flag: require('../assets/images/flags/sd.png'),
  },
  {
    name: 'Suriname',
    dial_code: '+597',
    code: 'SR',
    flag: require('../assets/images/flags/sr.png'),
  },
  {
    name: 'Svalbard and Jan Mayen',
    dial_code: '+47',
    code: 'SJ',
    flag: require('../assets/images/flags/sj.png'),
  },
  {
    name: 'Swaziland',
    dial_code: '+268',
    code: 'SZ',
    flag: require('../assets/images/flags/sz.png'),
  },
  {
    name: 'Sweden',
    dial_code: '+46',
    code: 'SE',
    flag: require('../assets/images/flags/se.png'),
  },
  {
    name: 'Switzerland',
    dial_code: '+41',
    code: 'CH',
    flag: require('../assets/images/flags/ch.png'),
  },
  {
    name: 'Syrian Arab Republic',
    dial_code: '+963',
    code: 'SY',
    flag: require('../assets/images/flags/sy.png'),
  },
  {
    name: 'Taiwan',
    dial_code: '+886',
    code: 'TW',
    flag: require('../assets/images/flags/tw.png'),
  },
  {
    name: 'Tajikistan',
    dial_code: '+992',
    code: 'TJ',
    flag: require('../assets/images/flags/tj.png'),
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    dial_code: '+255',
    code: 'TZ',
    flag: require('../assets/images/flags/tz.png'),
  },
  {
    name: 'Thailand',
    dial_code: '+66',
    code: 'TH',
    flag: require('../assets/images/flags/th.png'),
  },
  {
    name: 'Timor-Leste',
    dial_code: '+670',
    code: 'TL',
    flag: require('../assets/images/flags/tl.png'),
  },
  {
    name: 'Togo',
    dial_code: '+228',
    code: 'TG',
    flag: require('../assets/images/flags/tg.png'),
  },
  {
    name: 'Tokelau',
    dial_code: '+690',
    code: 'TK',
    flag: require('../assets/images/flags/tk.png'),
  },
  {
    name: 'Tonga',
    dial_code: '+676',
    code: 'TO',
    flag: require('../assets/images/flags/to.png'),
  },
  {
    name: 'Trinidad and Tobago',
    dial_code: '+1868',
    code: 'TT',
    flag: require('../assets/images/flags/tt.png'),
  },
  {
    name: 'Tunisia',
    dial_code: '+216',
    code: 'TN',
    flag: require('../assets/images/flags/tn.png'),
  },
  {
    name: 'Turkey',
    dial_code: '+90',
    code: 'TR',
    flag: require('../assets/images/flags/tr.png'),
  },
  {
    name: 'Turkmenistan',
    dial_code: '+993',
    code: 'TM',
    flag: require('../assets/images/flags/tm.png'),
  },
  {
    name: 'Turks and Caicos Islands',
    dial_code: '+1649',
    code: 'TC',
    flag: require('../assets/images/flags/tc.png'),
  },
  {
    name: 'Tuvalu',
    dial_code: '+688',
    code: 'TV',
    flag: require('../assets/images/flags/tv.png'),
  },
  {
    name: 'Uganda',
    dial_code: '+256',
    code: 'UG',
    flag: require('../assets/images/flags/ug.png'),
  },
  {
    name: 'Ukraine',
    dial_code: '+380',
    code: 'UA',
    flag: require('../assets/images/flags/ua.png'),
  },
  {
    name: 'United Arab Emirates',
    dial_code: '+971',
    code: 'AE',
    flag: require('../assets/images/flags/ae.png'),
  },
  {
    name: 'United Kingdom',
    dial_code: '+44',
    code: 'GB',
    flag: require('../assets/images/flags/gb.png'),
  },
  {
    name: 'United States',
    dial_code: '+1',
    code: 'US',
    flag: require('../assets/images/flags/us.png'),
  },
  {
    name: 'Uruguay',
    dial_code: '+598',
    code: 'UY',
    flag: require('../assets/images/flags/uy.png'),
  },
  {
    name: 'Uzbekistan',
    dial_code: '+998',
    code: 'UZ',
    flag: require('../assets/images/flags/uz.png'),
  },
  {
    name: 'Vanuatu',
    dial_code: '+678',
    code: 'VU',
    flag: require('../assets/images/flags/vu.png'),
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    dial_code: '+58',
    code: 'VE',
    flag: require('../assets/images/flags/ve.png'),
  },
  {
    name: 'Vietnam',
    dial_code: '+84',
    code: 'VN',
    flag: require('../assets/images/flags/vn.png'),
  },
  {
    name: 'Virgin Islands, British',
    dial_code: '+1284',
    code: 'VG',
    flag: require('../assets/images/flags/vg.png'),
  },
  {
    name: 'Virgin Islands, U.S.',
    dial_code: '+1340',
    code: 'VI',
    flag: require('../assets/images/flags/vi.png'),
  },
  {
    name: 'Wallis and Futuna',
    dial_code: '+681',
    code: 'WF',
    flag: require('../assets/images/flags/wf.png'),
  },
  {
    name: 'Yemen',
    dial_code: '+967',
    code: 'YE',
    flag: require('../assets/images/flags/ye.png'),
  },
  {
    name: 'Zambia',
    dial_code: '+260',
    code: 'ZM',
    flag: require('../assets/images/flags/zm.png'),
  },
  {
    name: 'Zimbabwe',
    dial_code: '+263',
    code: 'ZW',
    flag: require('../assets/images/flags/zw.png'),
  },
];
