export const demoEvents = [
  {
    event_id: 1,
    event_name: 'Tech Innovators Summit',
    ems_secret_code: 'DEMO1',
    nice_start_datetime: '2024-06-01 10:00',
    event_type_name: 'Type Démo',
    participants: [
      {
        participant_id: 1,
        first_name: 'Alice',
        last_name: 'Smith',
        phone: '+33621973611',
        email: 'alice.smith@example.com',
        organization: 'Google',
      },
      {
        participant_id: 2,
        first_name: 'Bob',
        last_name: 'Johnson',
        phone: '+33621973612',
        email: 'bob.johnson@example.com',
        organization: 'Microsoft',
      },
      {
        participant_id: 3,
        first_name: 'Charlie',
        last_name: 'Williams',
        phone: '+33621973613',
        email: 'charlie.williams@example.com',
        organization: 'Apple',
      },
      {
        participant_id: 4,
        first_name: 'David',
        last_name: 'Brown',
        phone: '+33621973614',
        email: 'david.brown@example.com',
        organization: 'Amazon',
      },
      {
        participant_id: 5,
        first_name: 'Eva',
        last_name: 'Jones',
        phone: '+33621973615',
        email: 'eva.jones@example.com',
        organization: 'Facebook',
      },
      {
        participant_id: 6,
        first_name: 'Frank',
        last_name: 'Garcia',
        phone: '+33621973616',
        email: 'frank.garcia@example.com',
        organization: 'Tesla',
      },
      {
        participant_id: 7,
        first_name: 'Grace',
        last_name: 'Martinez',
        phone: '+33621973617',
        email: 'grace.martinez@example.com',
        organization: 'Netflix',
      },
      {
        participant_id: 8,
        first_name: 'Hank',
        last_name: 'Robinson',
        phone: '+33621973618',
        email: 'hank.robinson@example.com',
        organization: 'Adobe',
      },
      {
        participant_id: 9,
        first_name: 'Ivy',
        last_name: 'Clark',
        phone: '+33621973619',
        email: 'ivy.clark@example.com',
        organization: 'Spotify',
      },
      {
        participant_id: 10,
        first_name: 'Jack',
        last_name: 'Rodriguez',
        phone: '+33621973620',
        email: 'jack.rodriguez@example.com',
        organization: 'Twitter',
      },
    ],
  },
  {
    event_id: 2,
    event_name: 'Future of AI Conference',
    ems_secret_code: 'DEMO2',
    nice_start_datetime: '2024-06-02 11:00',
    event_type_name: 'Type Démo',
    participants: [
      {
        participant_id: 11,
        first_name: 'Laura',
        last_name: 'Lee',
        phone: '+33621973621',
        email: 'laura.lee@example.com',
        organization: 'IBM',
      },
      {
        participant_id: 12,
        first_name: 'Mike',
        last_name: 'Walker',
        phone: '+33621973622',
        email: 'mike.walker@example.com',
        organization: 'Oracle',
      },
      {
        participant_id: 13,
        first_name: 'Nina',
        last_name: 'Hall',
        phone: '+33621973623',
        email: 'nina.hall@example.com',
        organization: 'SAP',
      },
      {
        participant_id: 14,
        first_name: 'Oscar',
        last_name: 'Allen',
        phone: '+33621973624',
        email: 'oscar.allen@example.com',
        organization: 'Salesforce',
      },
      {
        participant_id: 15,
        first_name: 'Paul',
        last_name: 'Young',
        phone: '+33621973625',
        email: 'paul.young@example.com',
        organization: 'Cisco',
      },
      {
        participant_id: 16,
        first_name: 'Quincy',
        last_name: 'King',
        phone: '+33621973626',
        email: 'quincy.king@example.com',
        organization: 'Intel',
      },
      {
        participant_id: 17,
        first_name: 'Rachel',
        last_name: 'Wright',
        phone: '+33621973627',
        email: 'rachel.wright@example.com',
        organization: 'HP',
      },
      {
        participant_id: 18,
        first_name: 'Steve',
        last_name: 'Lopez',
        phone: '+33621973628',
        email: 'steve.lopez@example.com',
        organization: 'Dell',
      },
      {
        participant_id: 19,
        first_name: 'Tina',
        last_name: 'Hill',
        phone: '+33621973629',
        email: 'tina.hill@example.com',
        organization: 'Nvidia',
      },
      {
        participant_id: 20,
        first_name: 'Uma',
        last_name: 'Scott',
        phone: '+33621973630',
        email: 'uma.scott@example.com',
        organization: 'AMD',
      },
    ],
  },
  {
    event_id: 3,
    event_name: 'Green Energy Expo',
    ems_secret_code: 'DEMO3',
    nice_start_datetime: 'Healthcare Revolution Forum',
    event_type_name: 'Type Démo',
    participants: [
      {
        participant_id: 21,
        first_name: 'Victor',
        last_name: 'Green',
        phone: '+33621973631',
        email: 'victor.green@example.com',
        organization: 'LG',
      },
      {
        participant_id: 22,
        first_name: 'Wendy',
        last_name: 'Adams',
        phone: '+33621973632',
        email: 'wendy.adams@example.com',
        organization: 'Samsung',
      },
      {
        participant_id: 23,
        first_name: 'Xander',
        last_name: 'Nelson',
        phone: '+33621973633',
        email: 'xander.nelson@example.com',
        organization: 'Sony',
      },
      {
        participant_id: 24,
        first_name: 'Yara',
        last_name: 'Carter',
        phone: '+33621973634',
        email: 'yara.carter@example.com',
        organization: 'Panasonic',
      },
      {
        participant_id: 25,
        first_name: 'Zane',
        last_name: 'Mitchell',
        phone: '+33621973635',
        email: 'zane.mitchell@example.com',
        organization: 'Philips',
      },
      {
        participant_id: 26,
        first_name: 'Abby',
        last_name: 'Perez',
        phone: '+33621973636',
        email: 'abby.perez@example.com',
        organization: 'Toshiba',
      },
      {
        participant_id: 27,
        first_name: 'Brian',
        last_name: 'Roberts',
        phone: '+33621973637',
        email: 'brian.roberts@example.com',
        organization: 'Hitachi',
      },
      {
        participant_id: 28,
        first_name: 'Clara',
        last_name: 'Turner',
        phone: '+33621973638',
        email: 'clara.turner@example.com',
        organization: 'Sharp',
      },
      {
        participant_id: 29,
        first_name: 'Daniel',
        last_name: 'Parker',
        phone: '+33621973639',
        email: 'daniel.parker@example.com',
        organization: 'JVC',
      },
      {
        participant_id: 30,
        first_name: 'Emily',
        last_name: 'Evans',
        phone: '+33621973640',
        email: 'emily.evans@example.com',
        organization: 'Sanyo',
      },
    ],
  },
  {
    event_id: 4,
    event_name: 'Événement Démo 4',
    ems_secret_code: 'DEMO4',
    nice_start_datetime: '2024-06-04 13:00',
    event_type_name: 'Type Démo',
    participants: [
      {
        participant_id: 31,
        first_name: 'Fiona',
        last_name: 'Garcia',
        phone: '+33621973641',
        email: 'fiona.garcia@example.com',
        organization: 'Pioneer',
      },
      {
        participant_id: 32,
        first_name: 'George',
        last_name: 'Morris',
        phone: '+33621973642',
        email: 'george.morris@example.com',
        organization: 'Kenwood',
      },
      {
        participant_id: 33,
        first_name: 'Hannah',
        last_name: 'Peterson',
        phone: '+33621973643',
        email: 'hannah.peterson@example.com',
        organization: 'Marantz',
      },
      {
        participant_id: 34,
        first_name: 'Isaac',
        last_name: 'Reed',
        phone: '+33621973644',
        email: 'isaac.reed@example.com',
        organization: 'Yamaha',
      },
      {
        participant_id: 35,
        first_name: 'Jasmine',
        last_name: 'Bailey',
        phone: '+33621973645',
        email: 'jasmine.bailey@example.com',
        organization: 'Denon',
      },
      {
        participant_id: 36,
        first_name: 'Kevin',
        last_name: 'Rivera',
        phone: '+33621973646',
        email: 'kevin.rivera@example.com',
        organization: 'Onkyo',
      },
      {
        participant_id: 37,
        first_name: 'Lily',
        last_name: 'Price',
        phone: '+33621973647',
        email: 'lily.price@example.com',
        organization: 'Pyle',
      },
      {
        participant_id: 38,
        first_name: 'Mason',
        last_name: 'Sanders',
        phone: '+33621973648',
        email: 'mason.sanders@example.com',
        organization: 'Polk Audio',
      },
      {
        participant_id: 39,
        first_name: 'Natalie',
        last_name: 'Bennett',
        phone: '+33621973649',
        email: 'natalie.bennett@example.com',
        organization: 'Bose',
      },
      {
        participant_id: 40,
        first_name: 'Oliver',
        last_name: 'Brooks',
        phone: '+33621973650',
        email: 'oliver.brooks@example.com',
        organization: 'JBL',
      },
    ],
  },
  {
    event_id: 5,
    event_name: 'Blockchain World Congress',
    ems_secret_code: 'DEMO5',
    nice_start_datetime: '2024-06-05 14:00',
    event_type_name: 'Type Démo',
    participants: [
      {
        participant_id: 41,
        first_name: 'Pamela',
        last_name: 'Gray',
        phone: '+33621973651',
        email: 'pamela.gray@example.com',
        organization: 'Harman',
      },
      {
        participant_id: 42,
        first_name: 'Quentin',
        last_name: 'Cruz',
        phone: '+33621973652',
        email: 'quentin.cruz@example.com',
        organization: 'Bang & Olufsen',
      },
      {
        participant_id: 43,
        first_name: 'Rita',
        last_name: 'Russell',
        phone: '+33621973653',
        email: 'rita.russell@example.com',
        organization: 'Klipsch',
      },
      {
        participant_id: 44,
        first_name: 'Sam',
        last_name: 'Fisher',
        phone: '+33621973654',
        email: 'sam.fisher@example.com',
        organization: 'KEF',
      },
      {
        participant_id: 45,
        first_name: 'Tina',
        last_name: 'Morgan',
        phone: '+33621973655',
        email: 'tina.morgan@example.com',
        organization: 'Bowers & Wilkins',
      },
      {
        participant_id: 46,
        first_name: 'Ursula',
        last_name: 'Bell',
        phone: '+33621973656',
        email: 'ursula.bell@example.com',
        organization: 'Dynaudio',
      },
      {
        participant_id: 47,
        first_name: 'Victor',
        last_name: 'Reyes',
        phone: '+33621973657',
        email: 'victor.reyes@example.com',
        organization: 'Focal',
      },
      {
        participant_id: 48,
        first_name: 'Wendy',
        last_name: 'Reed',
        phone: '+33621973658',
        email: 'wendy.reed@example.com',
        organization: 'Paradigm',
      },
      {
        participant_id: 49,
        first_name: 'Xavier',
        last_name: 'Howard',
        phone: '+33621973659',
        email: 'xavier.howard@example.com',
        organization: 'GoldenEar',
      },
      {
        participant_id: 50,
        first_name: 'Yvonne',
        last_name: 'James',
        phone: '+33621973660',
        email: 'yvonne.james@example.com',
        organization: 'Sonos',
      },
    ],
  },
];
